### ISSUE TITLE
Tracker makes KMF crash when removing modelelement contained in another modelElem

### ISSUE THREAD

**Issue by ahervieu** [dukeboard/kevoree-modeling-framework#59]
A Model Elm PCM contains a set of Matrices.
When PCM is tracked, calling removeAllMatrices provokes this exeception : 
Exception in thread "main" java.lang.ClassCastException: java.util.ArrayList cannot be cast to org.kevoree.modeling.api.KMFContainer
	at org.kevoree.modeling.api.trace.Event2Trace.inverse(Event2Trace.kt:63)
	at org.kevoree.modeling.api.util.ModelTracker.elementChanged(ModelTracker.kt:30)
	at kpcmmm.container.KMFContainerImpl$$TImpl.fireModelEventOnTree(KMFContainerImpl.kt:173)
	at kpcmmm.impl.kPCMImpl.fireModelEventOnTree(kPCMImpl.kt)
	at kpcmmm.container.KMFContainerImpl$$TImpl.fireModelEvent(KMFContainerImpl.kt:142)
	at kpcmmm.impl.kPCMImpl.fireModelEvent(kPCMImpl.kt)
	at kpcmmm.impl.kPCMImpl.internal_removeAllMatrices(kPCMImpl.kt:428)
	at kpcmmm.impl.kPCMImpl.removeAllMatrices(kPCMImpl.kt:398)
	at main.main(main.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

When it is not tracked, it behaves correctly

**Comment by dukeboard** [comment]
Tracker is deprecated in KMFv4
